# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Roguelike-Utils
version:      0.4.187
version_from: 
installdirs:  site
requires:
    Term::ReadKey:                 0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
